"""
Qobuz engine — wraps the `streamrip` CLI.

Streamrip is a Python package (``pip install streamrip``) that provides a
single ``rip`` command for Qobuz, Tidal, Deezer and SoundCloud. We invoke it
as a subprocess and parse stdout to report progress back to the UI.

Auth: the user supplies tokens via Settings → Qobuz (same pattern as Deezer
ARL). Two modes supported:

  * **Token mode**: ``qobuz-user-id`` + ``qobuz-auth-token`` (from play.qobuz.com
    cookies — look for ``user-id`` and ``user-auth-token``).
  * **Email + password mode**: ``qobuz-email`` + ``qobuz-password`` (we compute
    the md5 ourselves before writing streamrip's config).

app_id / secrets are optional — streamrip has a fallback list built in.
"""
from __future__ import annotations

import hashlib
import re
from pathlib import Path

from .base import EngineBase, EngineResult
from .registry import register
from ripster import http_client as _HTTP
from .streamrip_utils import (
    COMMON_TOML_SECTIONS,
    RE_CONFIG_MISMATCH,
    RE_ERROR,
    RE_TRACK_DONE,
    StreamripMixin,
    classify_line as _classify_line,
    find_rip,
    parse_progress as _parse_progress,
    write_config,
)

_QOBUZ_DEFAULT_APP_ID = "312369995"

_RE_AUTHFAIL = re.compile(
    r'auth.*(failed|invalid)|invalid.*(token|credentials)|'
    r'unauthorized|not\s+logged|login failed|AuthenticationError',
    re.I,
)

# Detect actual quality from streamrip output paths: [FLAC] [24B-96.0kHz] etc.
_RE_QUALITY_FOLDER = re.compile(
    r'\[(?P<fmt>FLAC|MP3|AAC)\](?:\s*\[(?P<bits>\d+)B-(?P<rate>\d+(?:\.\d+)?)kHz\])?',
    re.I,
)


def _detect_actual_quality(log_text: str) -> str:
    """Parse the actual downloaded quality from streamrip folder/log output.
    Returns a quality ID matching QobuzEngine._QUALITIES, or "" if unknown.
    """
    m = _RE_QUALITY_FOLDER.search(log_text)
    if not m:
        return ""
    fmt = (m.group("fmt") or "").upper()
    if fmt == "MP3":
        return "5"
    bits = int(m.group("bits") or 0)
    rate = float(m.group("rate") or 0)
    if bits >= 20:
        return "27" if rate > 96 else "7"
    return "6"


def _write_config(user_cfg: dict, save_path: str) -> Path:
    """Write a minimal streamrip config.toml with the user's Qobuz creds."""
    user_id     = str(user_cfg.get("qobuz-user-id")    or "").strip()
    auth_token  = str(user_cfg.get("qobuz-auth-token") or "").strip()
    email       = str(user_cfg.get("qobuz-email")      or "").strip()
    password    = str(user_cfg.get("qobuz-password")   or "").strip()
    app_id      = str(user_cfg.get("qobuz-app-id")     or "").strip() or _QOBUZ_DEFAULT_APP_ID
    secrets_raw = str(user_cfg.get("qobuz-secrets")    or "").strip()

    if user_id and auth_token:
        use_token   = "true"
        email_field = user_id
        pass_field  = auth_token
    else:
        use_token   = "false"
        email_field = email
        pass_field  = hashlib.md5(password.encode()).hexdigest() if password else ""

    q_map = {"5": 1, "mp3_320": 1, "6": 2, "flac": 2, "7": 3, "hires": 3, "27": 4, "hires_max": 4}
    quality_level = q_map.get(
        user_cfg.get("quality") or user_cfg.get("qobuz-quality") or "7", 3,
    )

    secrets_toml = "[]"
    if secrets_raw:
        parts = [f'"{p.strip()}"' for p in secrets_raw.split(",") if p.strip()]
        secrets_toml = "[" + ", ".join(parts) + "]"

    safe_save = save_path.replace("\\", "/")

    toml = (
        '# Auto-generated by Ripster — overwritten on every Qobuz download.\n\n'
        '[downloads]\n'
        f'folder = "{safe_save}"\n'
        'source_subdirectories = false\n'
        'concurrency = true\n'
        'max_connections = 6\n'
        'requests_per_minute = 60\n\n'
        '[qobuz]\n'
        f'quality = {quality_level}\n'
        'download_booklets = true\n'
        f'use_auth_token = {use_token}\n'
        f'email_or_userid = "{email_field}"\n'
        f'password_or_token = "{pass_field}"\n'
        f'app_id = "{app_id}"\n'
        f'secrets = {secrets_toml}\n\n'
        '[tidal]\n'
        'quality = 3\n'
        'download_videos = false\n'
        'user_id = ""\n'
        'country_code = ""\n'
        'access_token = ""\n'
        'refresh_token = ""\n'
        'token_expiry = ""\n\n'
        + COMMON_TOML_SECTIONS +
        '\n[filepaths]\n'
        # true → single-track downloads (per-track expansion sends one track URL
        # at a time) get their own folder instead of landing loose in the
        # save-path root, where /api/download-file cannot find them.
        'add_singles_to_folder = true\n'
        'folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"\n'
        'track_format = "{tracknumber:02}. {artist} - {title}{explicit}"\n'
        'restrict_characters = false\n'
        'truncate_to = 120\n\n'
        '[lastfm]\n'
        'source = "qobuz"\n'
        'fallback_source = ""\n'
    )
    return write_config(toml)


def _resolve_upc_to_album_id(upc: str, app_id: str, token: str = "") -> str | None:
    """Resolve a play.qobuz.com UPC barcode to a real qobuz_id via /album/search.

    streamrip passes UPCs straight to /album/get which returns nothing and hangs.
    Returns the alphanumeric slug on success, None if resolution failed.
    Synchronous — 3-second timeout keeps the queue responsive if Qobuz is slow.
    """
    import httpx as _httpx

    def _good_id(candidate: str) -> bool:
        # Qobuz sometimes returns id == upc in search results — that's useless.
        return bool(candidate) and candidate != upc

    try:
        headers = {"X-User-Auth-Token": token} if token else {}
        with _httpx.Client(timeout=3.0) as c:
            r = c.get(
                "https://www.qobuz.com/api.json/0.2/album/search",
                params={"query": upc, "limit": 5, "app_id": app_id},
                headers=headers,
            )
            if r.status_code != 200:
                return None
            data = r.json()
        items = (data.get("albums") or {}).get("items") or []
        for item in items:
            if str(item.get("upc", "") or "") == upc:
                candidate = str(item.get("id", "") or "")
                if _good_id(candidate):
                    return candidate
        real_items = [it for it in items if _good_id(str(it.get("id", "") or ""))]
        if len(real_items) == 1:
            return str(real_items[0].get("id", "")) or None
        return None
    except Exception:
        return None


@register
class QobuzEngine(StreamripMixin, EngineBase):
    name = "qobuz"

    def __init__(self):
        StreamripMixin.__init__(self)

    _QUALITIES = [
        {"id": "27", "label": "Hi-Res 24/192", "sub": "24-bit / up to 192 kHz", "badge": "HI-RES",   "color": "#ffd60a", "bitrate": "3000+ kbps", "ext": "flac", "req": "premium", "flag": "-q 4"},
        {"id": "7",  "label": "Hi-Res 24/96",  "sub": "24-bit / up to 96 kHz",  "badge": "HI-RES",   "color": "#ffd60a", "bitrate": "~2500 kbps", "ext": "flac", "req": "premium", "flag": "-q 3"},
        {"id": "6",  "label": "FLAC 16/44.1",  "sub": "CD quality lossless",    "badge": "LOSSLESS", "color": "#3ecfaa", "bitrate": "1411 kbps",  "ext": "flac", "req": "free",    "flag": "-q 2"},
        {"id": "5",  "label": "MP3 320",       "sub": "Lossy",                  "badge": "LOSSY",    "color": "#EF9F27", "bitrate": "320 kbps",   "ext": "mp3",  "req": "free",    "flag": "-q 1"},
    ]

    def qualities(self) -> list[dict]:
        return [{**q, "engine": self.name} for q in self._QUALITIES]

    def build_cmd(self, url: str, quality: str, config: dict) -> list[str]:
        save_path = config.get("qobuz-save-path") or config.get("save-path") or "downloads"
        Path(save_path).mkdir(parents=True, exist_ok=True)

        import urllib.parse as _up
        _parts = [p for p in _up.urlparse(url).path.split("/") if p]
        if _parts and _parts[-1].isdigit() and len(_parts[-1]) >= 12:
            upc    = _parts[-1]
            app_id = (config.get("qobuz-app-id") or "").strip() or _QOBUZ_DEFAULT_APP_ID
            token  = (config.get("qobuz-auth-token") or "").strip()
            print(f"[qobuz] Resolving UPC {upc} to album_id...", flush=True)
            real_id = _resolve_upc_to_album_id(upc, app_id, token)
            # IMPORTANT: use open.qobuz.com — streamrip's URL parser does NOT match
            # www.qobuz.com/album/{id} (no slug) and silently downloads 0 tracks
            # (exit 0). open.qobuz.com/album/{id} parses + downloads correctly.
            if real_id:
                url = f"https://open.qobuz.com/album/{real_id}"
                print(f"[qobuz] ✓ UPC resolved → album_id {real_id}", flush=True)
            else:
                url = f"https://open.qobuz.com/album/{upc}"
                print(f"[qobuz] UPC {upc}: no slug, using id directly (open.qobuz.com)", flush=True)
        else:
            # Normalize ANY qobuz album/track/playlist URL to open.qobuz.com/{type}/{id}.
            # Search results look like www.qobuz.com/fr-fr/album/{slug}/{id} (locale +
            # slug, id may be alphanumeric). streamrip's parser chokes on that form and
            # downloads 0 tracks (exit 0). The id is the last path segment.
            _m = re.search(
                r'qobuz\.com/(?:[a-z]{2}-[a-z]{2}/)?(album|track|playlist|artist)/(?:[^/]+/)?([A-Za-z0-9]+)/?$',
                url)
            if _m:
                url = f"https://open.qobuz.com/{_m.group(1)}/{_m.group(2)}"
                print(f"[qobuz] normalized URL → {url}", flush=True)

        cfg_copy = dict(config)
        cfg_copy["quality"] = quality
        cfg_path = _write_config(cfg_copy, save_path)
        # NOTE: do NOT pass --no-progress. streamrip 2.0.6 then prints nothing at
        # all when piped (non-TTY), so is_finished can't tell a real download from
        # a no-op. Without it, rich suppresses the live bar on a non-TTY but still
        # prints the "---- Downloading <title> ----" header we use as the success
        # signal. (No progress-bar spam results — rich detects the non-TTY.)
        return [find_rip(), "--config-path", str(cfg_path), "url", url]

    def classify_line(self, line: str) -> str:
        return _classify_line(line)

    def parse_progress(self, line: str, current: int, total: int) -> tuple[int, int]:
        return _parse_progress(line, current, total)

    def is_finished(self, log_text: str, rc: int = -1) -> EngineResult:
        # Windows-only: streamrip crashes with PermissionError while cleaning up
        # the __artwork temp folder AFTER the track is already downloaded and tagged.
        if "PermissionError" in log_text and "__artwork" in log_text:
            ok = RE_TRACK_DONE.findall(log_text)
            return EngineResult(success=True, tracks_ok=len(ok) or 1)

        m = RE_CONFIG_MISMATCH.search(log_text)
        if m and _RE_AUTHFAIL.search(log_text):
            return EngineResult(
                success=False,
                error=(f"streamrip config mismatch ({m.group(1)}→{m.group(2)}) + auth fail. "
                       f"Удали %APPDATA%\\streamrip\\config.toml и попробуй снова."),
            )

        if "IneligibleError" in log_text or "Free accounts are not eligible" in log_text:
            return EngineResult(
                success=False,
                error="Qobuz: бесплатный аккаунт — скачивание недоступно. Нужна платная подписка Qobuz.",
            )

        if _RE_AUTHFAIL.search(log_text):
            # Email/password login failure looks different from a stale cookie
            # token — streamrip logs the rejected params. Give the right hint.
            if "Invalid credentials from params" in log_text and "'email'" in log_text:
                return EngineResult(
                    success=False,
                    error="Qobuz: email или пароль отклонены (401). Проверь пароль точь-в-точь; "
                          "если не помогает — войди на play.qobuz.com в браузере и используй "
                          "Токен-режим (user-id + user-auth-token из cookies) — он надёжнее.",
                )
            return EngineResult(
                success=False,
                error="Qobuz: токен недействителен. Обнови qobuz-auth-token и qobuz-user-id "
                      "в Settings → Qobuz (DevTools → Cookies → play.qobuz.com).",
            )

        actual_q    = _detect_actual_quality(log_text)
        err_markers = re.findall(r'Failed to download|\berror:', log_text, re.I)
        if err_markers:
            last = ""
            for ln in reversed(log_text.splitlines()):
                if RE_ERROR.search(ln):
                    last = ln.strip()
                    break
            return EngineResult(success=False, error=last or "Qobuz: ошибка")

        # streamrip 2.0.6 renders per-track completion in a rich progress bar that
        # leaves NO text marker when piped (non-TTY). The one reliable textual
        # signal that it actually processed something is the per-album/playlist
        # header "---- Downloading <title> ----". (RE_TRACK_DONE is kept as a
        # belt-and-suspenders for builds that DO emit text markers.)
        ok_markers = RE_TRACK_DONE.findall(log_text)
        dl_markers = re.findall(r"Downloading\s+\S", log_text)
        n_ok = len(ok_markers) or len(dl_markers)
        if n_ok:
            return EngineResult(success=True, tracks_ok=n_ok, quality_actual=actual_q)
        # Skipped-because-already-downloaded is a legit success too.
        if re.search(r"already exists|Skipping", log_text, re.I):
            return EngineResult(success=True, quality_actual=actual_q)
        # rc==0 but streamrip printed NO "Downloading" header and no error = it
        # parsed nothing / matched no tracks (unrecognised URL, empty album, or a
        # raw UPC it couldn't resolve). That is the real 0-tracks failure — surface
        # it instead of a fake "done".
        return EngineResult(
            success=False,
            error="Qobuz: 0 треков — streamrip не распознал ссылку или альбом недоступен. "
                  "Проверь ссылку/подписку; запусти `rip --version`, если повторяется.",
        )

    async def search(self, query: str, search_type: str, limit: int, config: dict) -> list[dict]:
        import httpx as _httpx
        app_id = (config.get("qobuz-app-id") or "").strip() or _QOBUZ_DEFAULT_APP_ID
        token  = (config.get("qobuz-auth-token") or "").strip()
        ep_url_map = {"album": "album",  "track": "track",  "artist": "artist"}
        ep_key_map = {"album": "albums", "track": "tracks", "artist": "artists"}
        ep_url = ep_url_map.get(search_type, "album")
        ep_key = ep_key_map.get(search_type, "albums")
        try:
            async with _HTTP.ashared() as c:
                r = await c.get(
                    f"https://www.qobuz.com/api.json/0.2/{ep_url}/search",
                    params={"query": query, "limit": limit, "app_id": app_id},
                    headers={"X-User-Auth-Token": token} if token else {},
                )
                data = r.json()
            results = []
            for item in (data.get(ep_key) or {}).get("items") or []:
                full_date = item.get("release_date_original") or ""
                img = item.get("image") or {}
                results.append({
                    "id":      str(item.get("id", "")),
                    "title":   item.get("title") or item.get("name", ""),
                    "artist":  (item.get("artist") or {}).get("name", ""),
                    "type":    search_type,
                    "url":     (item.get("url") or
                                f"https://www.qobuz.com/album/{item.get('id', '')}"),
                    "cover":   (img.get("small") or img.get("large", "")) if isinstance(img, dict) else "",
                    "year":    full_date[:4],
                    "date":    full_date,
                    "label":   (item.get("label") or {}).get("name", "")
                               if isinstance(item.get("label"), dict) else "",
                    "hires":   item.get("hires", False),
                    "tracks":  item.get("tracks_count"),
                    "service": "qobuz",
                })
            return results
        except Exception:
            return []

    async def get_artist(self, artist_id: str, types: str, config: dict) -> dict:
        import httpx as _httpx
        app_id = (config.get("qobuz-app-id") or "").strip() or _QOBUZ_DEFAULT_APP_ID
        token  = (config.get("qobuz-auth-token") or "").strip()
        wanted = {t.strip() for t in types.split(",") if t.strip()}
        try:
            async with _HTTP.ashared() as c:
                headers = {"X-User-Auth-Token": token} if token else {}
                ar = await c.get("https://www.qobuz.com/api.json/0.2/artist/get", params={
                    "artist_id": artist_id, "extra": "albums", "limit": 200, "app_id": app_id,
                }, headers=headers)
                data = ar.json()
            if data.get("status") == "error":
                return {"error": data.get("message", "Qobuz error"), "releases": []}
            artist = {
                "id":      str(data.get("id", artist_id)),
                "name":    data.get("name", ""),
                "picture": (data.get("image") or {}).get("large", "") if isinstance(data.get("image"), dict) else "",
                "albums_total": data.get("albums_count"),
                "url":     f"https://www.qobuz.com/artist/{artist_id}",
                "service": "qobuz",
            }
            releases = []
            for a in (data.get("albums") or {}).get("items", []):
                rtype = (a.get("release_type") or "album").lower()
                releases.append({
                    "id":      str(a.get("id", "")),
                    "title":   a.get("title", ""),
                    "cover":   (a.get("image") or {}).get("large", "") if isinstance(a.get("image"), dict) else "",
                    "year":    (a.get("release_date_original") or "")[:4],
                    "date":    a.get("release_date_original", ""),
                    "tracks":  a.get("tracks_count"),
                    "label":   (a.get("label") or {}).get("name", "") if isinstance(a.get("label"), dict) else "",
                    "type":    rtype,
                    "url":     a.get("url", "") or f"https://www.qobuz.com/album/{a.get('id', '')}",
                    "explicit":a.get("parental_warning", False),
                    "hires":   a.get("hires", False),
                    "service": "qobuz",
                })
            if wanted and wanted != {"all"}:
                releases = [r for r in releases if r["type"] in wanted]
            releases.sort(key=lambda r: r.get("date", ""), reverse=True)
            return {"artist": artist, "releases": releases}
        except Exception as e:
            return {"error": str(e), "releases": []}

    async def get_album(self, album_id: str, config: dict) -> dict:
        import httpx as _httpx
        app_id = (config.get("qobuz-app-id") or "").strip() or _QOBUZ_DEFAULT_APP_ID
        token  = (config.get("qobuz-auth-token") or "").strip()
        try:
            async with _HTTP.ashared() as c:
                headers = {"X-User-Auth-Token": token} if token else {}
                r = await c.get("https://www.qobuz.com/api.json/0.2/album/get", params={
                    "album_id": album_id, "app_id": app_id,
                }, headers=headers)
                a = r.json()
            if a.get("status") == "error":
                return {"error": a.get("message", "Qobuz error")}
            tracks = []
            for t in (a.get("tracks") or {}).get("items", []):
                tracks.append({
                    "id":       str(t.get("id", "")),
                    "title":    t.get("title", ""),
                    "artist":   (t.get("performer") or {}).get("name", "") if isinstance(t.get("performer"), dict) else "",
                    "duration": t.get("duration"),
                    "track_no": t.get("track_number"),
                    "disc":     t.get("media_number"),
                    "preview":  "",
                    "explicit": t.get("parental_warning", False),
                    "url":      f"https://www.qobuz.com/track/{t.get('id', '')}",
                })
            album_real_id = str(a.get("id", album_id))
            return {
                "album": {
                    "id":     album_real_id,
                    "title":  a.get("title", ""),
                    "artist": (a.get("artist") or {}).get("name", ""),
                    "cover":  (a.get("image") or {}).get("large", "") if isinstance(a.get("image"), dict) else "",
                    "year":   (a.get("release_date_original") or "")[:4],
                    "date":   a.get("release_date_original", ""),
                    "label":  (a.get("label") or {}).get("name", "") if isinstance(a.get("label"), dict) else "",
                    "upc":    a.get("upc", ""),
                    "genre":  (a.get("genre") or {}).get("name", "") if isinstance(a.get("genre"), dict) else "",
                    "tracks": a.get("tracks_count"),
                    "url":    a.get("url", "") or f"https://www.qobuz.com/album/{album_real_id}",
                    "service":"qobuz",
                },
                "tracks": tracks,
            }
        except Exception as e:
            return {"error": str(e)}
